info:
  name: config.info.version=2
spring:
  profiles: dev
  application:
    name: cloud-config-client
---
info:
  name: config.info.version=2
spring:
  profiles: test
  application:
    name: cloud-config-client
